language: python
services:
  - docker

# Pre-testing installs
install:
  # install awscli v2 if not available
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - mkdir models ~/.aws
  - echo "$AWS_CREDENTIALS" | base64 --decode > ~/.aws/credentials && echo "$AWS_CONFIG" | base64 --decode > ~/.aws/config
  - aws s3 sync s3://oclear-107898776944-bucket/models models
  - ls models

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build --compress -t oclear-fastapi:cpu-local .
  - docker tag oclear-fastapi:cpu-local asanjaata96/oclear-fastapi:cpu-local

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push asanjaata96/oclear-fastapi:cpu-local